package services

const (
	FeatureOnlineStore           = "online_store"
	FeatureMultiCurrency         = "multi_currency"
	FeatureExportDocuments       = "export_documents"
	FeatureSEZDocuments          = "sez_documents"
	FeatureDeemedExportDocuments = "deemed_export_documents"
	FeatureMultiUser             = "multi_user"
	FeatureCustomRoles           = "custom_roles"
	FeatureMultiBusiness         = "multi_business"
	FeatureBranches              = "branches"
	FeaturePrioritySupport       = "priority_support"
	FeatureDriveStorageMB        = "drive_storage_mb"
	FeatureWhatsAppNotifications = "whatsapp_notifications"
)

const (
	PermissionStorefrontManage      = "storefront.manage"
	PermissionStorefrontView        = "storefront.view"
	PermissionOrdersManage          = "orders.manage"
	PermissionOrdersView            = "orders.view"
	PermissionBranchesManage        = "branches.manage"
	PermissionBranchesView          = "branches.view"
	PermissionRolesManage           = "roles.manage"
	PermissionTeamsManage           = "teams.manage"
	PermissionTeamsView             = "teams.view"
	PermissionDocumentsManage       = "documents.manage"
	PermissionDocumentsExport       = "documents.export"
	PermissionCustomersCreate       = "customers.create"
	PermissionCustomersUpdate       = "customers.update"
	PermissionCustomersDelete       = "customers.delete"
	PermissionVendorsCreate         = "vendors.create"
	PermissionVendorsUpdate         = "vendors.update"
	PermissionVendorsDelete         = "vendors.delete"
	PermissionRenderProfilesCreate  = "render_profiles.create"
	PermissionRenderProfilesUpdate  = "render_profiles.update"
	PermissionRenderProfilesDelete  = "render_profiles.delete"
	PermissionProductsManage        = "products.manage"
	PermissionProductsView          = "products.view"
	PermissionPaymentsManage        = "payments.manage"
	PermissionPaymentsView          = "payments.view"
	PermissionDriveManage           = "drive.manage"
	PermissionDriveView             = "drive.view"
	PermissionNotificationsManage   = "notifications.manage"
	PermissionSubscriptionsManage   = "subscriptions.manage"
	PermissionSubscriptionsView     = "subscriptions.view"
	PermissionReportsExport         = "reports.export"
	PermissionReportsShare          = "reports.share"
	PermissionReportsView           = "reports.view"
	PermissionAccountingManage      = "accounting.manage"
	PermissionBankingManage         = "banking.manage"
	PermissionTaxIntegrationsManage = "tax.integrations.manage"
	PermissionPOSOperate            = "pos.operate"
	PermissionAgentsManage          = "agents.manage"
	PermissionAgentsView            = "agents.view"
	PermissionVoiceUse              = "voice:use"
)
