#!/bin/bash

# Configuration
TF_DIR="infrastructure/terraform"
ENV_FILE=".env"
REGION="us-east-1"

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}Starting .env generation...${NC}"

# Check requirements
if ! command -v terraform &> /dev/null; then
    echo -e "${RED}Error: terraform is not installed${NC}"
    exit 1
fi

if ! command -v aws &> /dev/null; then
    echo -e "${RED}Error: aws cli is not installed${NC}"
    exit 1
fi

if ! command -v jq &> /dev/null; then
    echo -e "${RED}Error: jq is not installed${NC}"
    exit 1
fi

# Go to Terraform directory to get outputs
if [ ! -d "$TF_DIR" ]; then
    echo -e "${RED}Error: Directory $TF_DIR does not exist${NC}"
    exit 1
fi

echo "Fetching Terraform outputs..."
cd "$TF_DIR" || exit
TF_OUTPUTS=$(terraform output -json)
cd - > /dev/null || exit

if [ -z "$TF_OUTPUTS" ]; then
    echo -e "${RED}Error: No Terraform outputs found. Did you run 'terraform apply'?${NC}"
    exit 1
fi

# Extract values from Terraform outputs
DB_HOST=$(echo "$TF_OUTPUTS" | jq -r '.rds_address.value // empty')
DB_PORT=$(echo "$TF_OUTPUTS" | jq -r '.rds_port.value // empty')
DB_NAME=$(echo "$TF_OUTPUTS" | jq -r '.rds_database_name.value // empty')
REDIS_HOST=$(echo "$TF_OUTPUTS" | jq -r '.elasticache_endpoint.value // empty')
REDIS_PORT=$(echo "$TF_OUTPUTS" | jq -r '.elasticache_port.value // empty')
COGNITO_USER_POOL_ID=$(echo "$TF_OUTPUTS" | jq -r '.user_pool_id.value // empty')
COGNITO_CLIENT_ID=$(echo "$TF_OUTPUTS" | jq -r '.client_id.value // empty')
S3_BUCKET_LOGOS=$(echo "$TF_OUTPUTS" | jq -r '.s3_bucket_logos.value // empty')
S3_BUCKET_INVOICES=$(echo "$TF_OUTPUTS" | jq -r '.s3_bucket_invoices.value // empty')
S3_BUCKET_PRODUCTS=$(echo "$TF_OUTPUTS" | jq -r '.s3_bucket_products.value // empty')
SQS_INVOICE_QUEUE=$(echo "$TF_OUTPUTS" | jq -r '.invoice_processing_queue_url.value // empty')
SQS_PAYMENT_QUEUE=$(echo "$TF_OUTPUTS" | jq -r '.payment_processing_queue_url.value // empty')
SNS_ALERTS_TOPIC_ARN=$(echo "$TF_OUTPUTS" | jq -r '.sns_alerts_topic_arn.value // empty')
ALB_DNS_NAME=$(echo "$TF_OUTPUTS" | jq -r '.alb_dns_name.value // empty')
API_GATEWAY_ENDPOINT=$(echo "$TF_OUTPUTS" | jq -r '.api_gateway_endpoint.value // empty')
ECS_CLUSTER_NAME=$(echo "$TF_OUTPUTS" | jq -r '.ecs_cluster_name.value // empty')
ECS_SERVICE_NAME=$(echo "$TF_OUTPUTS" | jq -r '.ecs_service_name.value // empty')
DB_SECRET_ARN=$(echo "$TF_OUTPUTS" | jq -r '.db_credentials_secret_arn.value // empty')

# Fetch Secrets
DB_USER=""
DB_PASSWORD=""

if [ -n "$DB_SECRET_ARN" ]; then
    echo "Fetching Database credentials from Secrets Manager..."
    SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id "$DB_SECRET_ARN" --region "$REGION" --query 'SecretString' --output text 2>/dev/null)
    if [ -n "$SECRET_VALUE" ]; then
        DB_USER=$(echo "$SECRET_VALUE" | jq -r '.username // empty')
        DB_PASSWORD=$(echo "$SECRET_VALUE" | jq -r '.password // empty')
    else
        echo -e "${RED}Warning: Could not fetch DB secret value${NC}"
    fi
fi

# Create .env content
cat > "$ENV_FILE" << EOF
# ===========================================
# Invoice Backend - Production/Staging Environment
# Auto-generated by scripts/generate_env.sh
# ===========================================

# Application Environment
ENVIRONMENT=production

# Server Configuration
SERVER_PORT=8080
SERVER_READ_TIMEOUT=30
SERVER_WRITE_TIMEOUT=30

# ===========================================
# Database Configuration (RDS PostgreSQL)
# ===========================================
DATABASE_HOST=${DB_HOST}
DATABASE_PORT=${DB_PORT}
DATABASE_USER=${DB_USER}
DATABASE_PASSWORD=${DB_PASSWORD}
DATABASE_NAME=${DB_NAME}
DATABASE_SSL_MODE=require

# ===========================================
# Redis Configuration (ElastiCache)
# ===========================================
REDIS_HOST=${REDIS_HOST}
REDIS_PORT=${REDIS_PORT}
REDIS_PASSWORD=
REDIS_DB=0

# ===========================================
# AWS Configuration
# Note: AWS Credentials should ideally be provided via IAM Roles or Profiles
# ===========================================
AWS_REGION=${REGION}
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=

# ===========================================
# Cognito Configuration
# ===========================================
COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
COGNITO_REGION=${REGION}
COGNITO_JWKS_REFRESH_RATE=10m

# ===========================================
# JWT Configuration
# ===========================================
JWT_ACCESS_TOKEN_EXPIRY=1h
JWT_REFRESH_TOKEN_EXPIRY=720h

# ===========================================
# S3 Bucket Configuration
# ===========================================
S3_BUCKET_LOGOS=${S3_BUCKET_LOGOS}
S3_BUCKET_INVOICES=${S3_BUCKET_INVOICES}
S3_BUCKET_PRODUCTS=${S3_BUCKET_PRODUCTS}
S3_BUCKET_EMAIL_SINK=

# ===========================================
# SQS Queue Configuration
# ===========================================
SQS_INVOICE_QUEUE=${SQS_INVOICE_QUEUE}
SQS_PAYMENT_QUEUE=${SQS_PAYMENT_QUEUE}

# ===========================================
# SNS Topics
# ===========================================
SNS_ALERTS_TOPIC_ARN=${SNS_ALERTS_TOPIC_ARN}

# ===========================================
# Additional Infrastructure
# ===========================================
ALB_DNS_NAME=${ALB_DNS_NAME}
API_GATEWAY_ENDPOINT=${API_GATEWAY_ENDPOINT}
ECS_CLUSTER_NAME=${ECS_CLUSTER_NAME}
ECS_SERVICE_NAME=${ECS_SERVICE_NAME}
EOF

echo -e "${GREEN}Successfully generated $ENV_FILE${NC}"
echo "You may need to manually fill in AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY if not running in an environment with IAM roles."
